from parallel_mining.parallel_miner import Prallel_miner
from parallel_mining.extract_texts import extract_texts
from parallel_mining.combine_files import combine_files_in_dir
from parallel_mining.split_file_by_lang import split_files_in_dir
