from utils_extract.parallel_miner import Prallel_miner
from utils_extract.extract_texts import extract_texts
from utils_extract.file_operation import files_combine, files_split
from utils_extract.language_detect import lang_detect
from utils_extract.shared import Reg_Exp
